language: python
python:
    - "2.6"
    - "2.7"
    #- "3.4"
    #- "3.5"
    - "pypy"
install:
    - pip install .
    - pip install mock pytest-cov
script: py.test --cov=ecmc --cov-report term-missing
